services:
  hexo:
    build: .
    container_name: hexo-container
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    
  nginx:
    image: nginx:alpine
    container_name: webserver-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - hexo
